### ISSUE TITLE
Guide to install

### ISSUE THREAD

**Issue by thansau239** [S03D4-164/Hiryu#1]
Dear,
Can you detail about that/
Edit myproject/settings.py
1. Add 'Hiryu' to INSTALLED_APPS
2. Edit DATABASES (postgresql is recommended)
3. Change ROOT_URLCONF => 'Hiryu.urls'
4. Add line => NEO4J_AUTH="<neo4j user>:<neo4j password>" 
   (or export above NEO4J_AUTH as env)

**Comment by S03D4-164** [comment]
Hello,
Thank you for interest in my app. (I wonder how you find it...)

The installation guide had a lot of problem because the app is a little old and I have left it as it was.
So I updated Readme.md and could confirm the app runs.

I have no confidence this app is currently useful, but hope it helps.
If I could find the time, I'd like to rewrite the code and create dockerfile, but can't promise it.

**Comment by thansau239** [comment]
dear,
Thank you for your response. I have already added exactly user/pass of NEO4J_AUTH="<neo4j user>:<neo4j password>"  to setting.py but it's error "401 anauthorized" 
Please help me fix it

**Comment by S03D4-164** [comment]
Sorry for my late reply.
I also confirmed NEO4J_AUTH env (and some cypher) does not work.
I fixed the problems and confirmed the app can connect to Neo4j.
Please update your local repository and change NEO4J_AUTH in Django's settings.py as follows:
```
NEO4J_AUTH = {
    "HOST": "localhost",
    "PORT": "7474",
    "USER": "<Neo4j user>",
    "PASS": "<Neo4j pass>",
}
```

**Comment by thansau239** [comment]
Thank you very much!
